version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      # - echo Installing Flutter SDK
      # - git clone https://github.com/flutter/flutter.git -b stable
      # - export PATH="$PATH:`pwd`/flutter/bin"
      - echo $STACK_ENV
      - echo $SPAN_FE_WEB_BUCKET_NAME
      

  pre_build:
    commands:
      - echo Starting build at `date`

  build:
    commands:
      - echo Building Flutter Web App

  post_build:
    commands:
      - echo Deploying Flutter Web to S3
      - echo "Unzipping the web build"
      - unzip web_build.zip -d web_build
      - echo "Copying the web build to S3"
      - aws s3 cp web_build s3://dev.spaninspect.com/ --recursive
      - echo "Removing the web build"
      - rm -rf web_build
      - echo "Creating CloudFront invalidation"
      - aws cloudfront create-invalidation --distribution-id E3FNXIM11E9RFO --paths "/*"
      - echo Deployment completed at `date`